services:
  nginx:
    image: nginx:alpine
    container_name: gateway-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app_1
      - app_2
    networks:
      - backend

  app_1:
    build: ./app_1
    container_name: app_1
    expose:
      - "8000"
    networks:
      - backend

  app_2:
    build: ./app_2
    container_name: app_2
    expose:
      - "8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
